### ISSUE TITLE
Hacer los quarks una dependencia obligatoria

### ISSUE THREAD

**Issue by diegodorado** [HuayraLinux/pkg-foxdot#2]
FosDot sin los quarks de SC no tiene utilidad... deberian ser una dependencia obligada, asi no tengo necesidad de instalarlos aparte.

Por otro lado comento que el nombre sc3-quarks es un poco inconducente, pq existen montones de quarks y aca hay solo unos pocos.... le llamaria sc3-foxdot-quarks

**Comment by ftoledo** [comment]
> FosDot sin los quarks de SC no tiene utilidad... deberian ser una dependencia obligada, asi no tengo necesidad de instalarlos aparte.

Hola @diegodorado , ahora lo agrego asi no hace falta instalar aparte, el paquete instala sc3-plugins porque los recomendados se instalan por defecto salvo que uses la opcion _--no-install-recommends_ de apt  y sc3-plugins instala sc3-plugins-server por dependencia, con lo cual con instalar python3-foxdot, ya tenes todos los paquetes!

> 
> Por otro lado comento que el nombre sc3-quarks es un poco inconducente, pq existen montones de quarks y aca hay solo unos pocos.... le llamaria sc3-foxdot-quarks 

Suena lógico, se puede renombrar

**Comment by ftoledo** [comment]
renombrado a sc3-foxdot-quarks
